### ISSUE TITLE
Getting started / submission

### ISSUE THREAD

**Issue by cameronjacoby** [sf-wdi-24/ruby-koans#1]
Can you make clear sections for "Getting Started" and "Submission"? Also, should they fork + clone this repo, then copy the `koans` directory into their copy of `ruby-koans`? It will be nested, but I think it's the best way they can make a PR.

Also, `develop` directory, not `dev` in this section: https://github.com/sf-wdi-24/ruby-koans/blob/master/README.md#about-ruby-koans

**Comment by ben-manning** [comment]
@cameronjacoby  I've made a few adjustments regarding the clarity of the assignment.  I agree that it was a little too vague on how to go about things.  As it stands they will be nesting the koans directory in the copy of this one.
